DROP SCHEMA IF EXISTS `SWADB`;
CREATE SCHEMA IF NOT EXISTS `SWADB` DEFAULT CHARACTER SET utf8 ;
USE `SWADB` ;

-- -----------------------------------------------------
-- Table `SWADB`.`TUSER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SWADB`.`TUSER` (
    `IDUSER` INT NOT NULL,
    `FIRSTNAME` VARCHAR(32) NULL,
    `LASTNAME` VARCHAR(32) NULL,
    `USERNAME` VARCHAR(32) NULL,
    `EMAIL` VARCHAR(32) NULL,
    `PASSWORD` VARCHAR(32) NULL,
    `ADMIN` TINYINT NULL,
    `COMPANYID` INT NOT NULL,
    PRIMARY KEY (`IDUSER`)
);
-- -----------------------------------------------------
-- Table `SWADB`.`TCOMPANY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SWADB`.`TCOMPANY` (
    `IDCOMPANY` INT NOT NULL,
    `NAME` VARCHAR(32) NULL,
    `DEPARTMENT` VARCHAR(32) NULL,
    `ADDRESS` VARCHAR(32) NULL,
    PRIMARY KEY (`IDCOMPANY`)
);

-- -----------------------------------------------------
-- Table `SWADB`.`TSERVICECONTRACT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SWADB`.`TSERVICECONTRACT` (
    `IDSERVICECONTRACT` INT NOT NULL,
    `STARTDATE` DATETIME NULL,
    `ENDDATE` DATETIME NULL,
    `COMPANYID` INT NOT NULL,
    `USERID` INT NOT NULL,
    PRIMARY KEY (`IDSERVICECONTRACT`)
);

-- -----------------------------------------------------
-- Table `SWADB`.`TLICENSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SWADB`.`TLICENSE` (
    `IDLICENSE` INT NOT NULL,
    `EXPIRATIONDATE` DATETIME NULL,
    `LICENSEKEY` VARCHAR(32) NULL,
    `LICENSECOUNT` INT NULL,
    `IP1` VARCHAR(15) NULL,
    `IP2` VARCHAR(15) NULL,
    `IP3` VARCHAR(15) NULL,
    `IP4` VARCHAR(15) NULL,
    `TSCID` INT NOT NULL,
    PRIMARY KEY (`IDLICENSE`)
);

-- -----------------------------------------------------
-- Connections between the tables
-- -----------------------------------------------------
ALTER TABLE TSERVICECONTRACT 
	ADD CONSTRAINT FK_TSC_TUSER 
	FOREIGN KEY (USERID) REFERENCES TUSER (IDUSER);
ALTER TABLE TSERVICECONTRACT 
	ADD CONSTRAINT FK_TSC_TCOMPANY 
	FOREIGN KEY (COMPANYID) REFERENCES TCOMPANY (IDCOMPANY);
ALTER TABLE TUSER 
	ADD CONSTRAINT FK_TUSER_TCOMPANY 
	FOREIGN KEY (COMPANYID) REFERENCES TCOMPANY (IDCOMPANY);
ALTER TABLE TLICENSE 
	ADD CONSTRAINT FK_TLICENSE_TSC 
	FOREIGN KEY (TSCID) REFERENCES TSERVICECONTRACT (IDSERVICECONTRACT);    
    

/* The following table IS NOT AN ENTITY!
 * It serves to manage the primary ke<s for each
 * table/entity.
 */
 
CREATE TABLE `SEQUENCE` (
    `SEQ_NAME` VARCHAR(255) NOT NULL,
    `SEQ_COUNT` INT(11) NOT NULL,
    PRIMARY KEY (`SEQ_NAME`)
)  ENGINE=INNODB;

INSERT INTO `SWADB`.`SEQUENCE` (`SEQ_NAME`,`SEQ_COUNT`) VALUES ('TUSER',1);
INSERT INTO `SWADB`.`SEQUENCE` (`SEQ_NAME`,`SEQ_COUNT`) VALUES ('TLICENSE',1);
INSERT INTO `SWADB`.`SEQUENCE` (`SEQ_NAME`,`SEQ_COUNT`) VALUES ('TSERVICECONTRACT',1);
INSERT INTO `SWADB`.`SEQUENCE` (`SEQ_NAME`,`SEQ_COUNT`) VALUES ('TCOMPANY',1);

